package org.codealpha.attendancesystem.dal.entity;
// Generated Apr 30, 2024 6:32:15 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AttendanceRecords generated by hbm2java
 */
@Entity
@Table(name="attendance_records"
    ,catalog="attendance_management_system_java"
)
public class AttendanceRecords  implements java.io.Serializable {


     private Integer id;
     private StudentsCources studentsCources;
     private Date attendanceDate;
     private String status;

    public AttendanceRecords() {
    }

    public AttendanceRecords(StudentsCources studentsCources, Date attendanceDate, String status) {
       this.studentsCources = studentsCources;
       this.attendanceDate = attendanceDate;
       this.status = status;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="students_cources_id", nullable=false)
    public StudentsCources getStudentsCources() {
        return this.studentsCources;
    }
    
    public void setStudentsCources(StudentsCources studentsCources) {
        this.studentsCources = studentsCources;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="attendance_date", nullable=false, length=10)
    public Date getAttendanceDate() {
        return this.attendanceDate;
    }
    
    public void setAttendanceDate(Date attendanceDate) {
        this.attendanceDate = attendanceDate;
    }

    
    @Column(name="status", nullable=false, length=10)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


